name: Beets Music Organizer
version: 0.0.19
slug: beets
description: A Home Assistant Add-On that uses beets to organize music files and enrich metadata.
options:
  MUSIC_INPUT_DIR: /media/download
  MUSIC_OUTPUT_DIR: /media/musik
  IMPORT_TIMEOUT: 60
schema:
  MUSIC_INPUT_DIR: str
  MUSIC_OUTPUT_DIR: str
  IMPORT_TIMEOUT: int
map:
  - media:rw
  - config:rw
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
